# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-12-24 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='姓名')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('sex', models.CharField(choices=[('0', 'male'), ('1', 'female')], max_length=10, verbose_name='性别')),
                ('email', models.CharField(max_length=11, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('avater', models.ImageField(upload_to='upload', verbose_name='头像')),
            ],
            options={
                'db_table': 'sp_user',
            },
        ),
    ]
