# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-12-25 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('pubdate', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('reads', models.ImageField(default=0, upload_to='', verbose_name='阅读数')),
                ('comments', models.ImageField(default=0, upload_to='', verbose_name='评论数')),
            ],
            options={
                'db_table': 'sp_book',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=100, verbose_name='人物')),
                ('skill', models.CharField(max_length=100, verbose_name='技能')),
                ('intro', models.CharField(max_length=100, verbose_name='简介')),
                ('weapon', models.CharField(max_length=100, verbose_name='武器')),
                ('hbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='user.Book', verbose_name='和图书的关系')),
            ],
            options={
                'db_table': 'sp_hero',
            },
        ),
    ]
